language: node_js
node_js:
  - "lts/*"
install:
  - npm ci || npm install
cache:
  directories:
  - "$HOME/.npm"
before_script:
  - npm install -g gulp-cli stylelint
  - gulp pretest
script:
  - stylelint "assets/styles/build/*.css"
notifications:
  slack: scottsmith:dyOlsu15eZFL1YmhpwngiFrf