language: node_js
node_js:
  - "lts/*"
install:
  - npm ci
cache:
  directories:
  - "$HOME/.npm"
before_script:
  - npm install npm@latest -g
  - npm install -g gulp-cli stylelint
  - gulp pretest
script:
  - stylelint "styles/build/*.css"
notifications:
  slack: scottsmith:dyOlsu15eZFL1YmhpwngiFrf