language: node_js
node_js:
  - "4"
before_script:
  - npm install -g gulp-cli stylelint
  - gulp pretest
script:
  - stylelint "styles/build/*.css"
notifications:
  slack: scottsmith:dyOlsu15eZFL1YmhpwngiFrf